name: Style checking with clang-format
on:
  push:
    paths: [ ".clang-format", "**/*.h", "**/*.cc", "**/*.cu" ]
  pull_request:
    paths: [ ".clang-format", "**/*.h", "**/*.cc", "**/*.cu" ]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: clang-format check
        run: >
          find . -type f \( -name '*.cc' -o -name '*.cu' -o -name '*.h' \)
          -exec clang-format -n --Werror {} +
